const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();tg?.setHeaderColor('#062968');tg?.setBackgroundColor('#062968');
const $=s=>document.querySelector(s),dialog=$('#command-dialog');let state={campaigns:[],tasks:[]},poll;
const api=(path,options={})=>fetch(path,{...options,headers:{'Content-Type':'application/json','x-telegram-init-data':tg?.initData||'',...(options.headers||{})}}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'تعذر تنفيذ الطلب');return d});
function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3000)}
function stateLabel(s){return({planned:'مخطط',awaiting_start:'بانتظار البدء',in_production:'قيد التنفيذ',in_review:'قيد المراجعة',ready_to_publish:'جاهز للنشر',published:'منشور',postponed:'مؤجل',cancelled:'ملغى'})[s]||s}
function render(data){state=data;const now=data.now;$('.date-line').textContent=`${now.weekday}، ${now.localDate} · ${now.time} — الخليل، فلسطين`;$('header .brand small').textContent=`CONTENT COMMAND · ${now.timezone}`;
  $('#planned-count').textContent=data.tasks.filter(t=>['planned','awaiting_start'].includes(t.status)).length;$('#production-count').textContent=data.tasks.filter(t=>['in_production','in_review'].includes(t.status)).length;
  $('#task-list').innerHTML=data.tasks.length?data.tasks.map(t=>`<article class="task ${t.status==='published'?'done':''}"><time>${stateLabel(t.status)}</time><div><b>${esc(t.title)}</b><p>${esc(t.description||'لا يوجد وصف إضافي.')}</p><span class="status">${t.locked?'مثبّت بعد بدء التنفيذ':'تحديث الحالة'}</span></div><button data-task="${t.id}" data-status="${t.status}">${t.status==='published'?'✓':'○'}</button></article>`).join(''):'<p class="empty">لا توجد مهام حقيقية بعد. أنشئ حملة ليضيف XPAND خطة تنفيذ قابلة للمراجعة.</p>';
  const active=data.campaigns.find(c=>c.status==='running'||c.status==='queued');const completed=data.campaigns.find(c=>c.status==='completed');
  $('.alerts').innerHTML=active?`<span class="alert-dot"></span><b>بحث جارٍ</b><p>${stageText(active.stage)}. يمكنك مغادرة الأداة والعودة؛ الحالة محفوظة.</p><button data-action="refresh">تحديث ←</button>`:`<span class="alert-dot"></span><b>الحالة</b><p>${data.note||'لا توجد تنبيهات تتطلب إجراء الآن.'}</p>`;
  const occasion=$('.occasion-card');occasion.innerHTML='<div class="occasion-head"><span class="tag">المناسبات</span><span>◌</span></div><h2>لا توجد مناسبة مؤكدة</h2><p>لن يعرض XPAND عدًا تنازليًا قبل التحقق من مصدر تاريخ صالح وملاءمة المناسبة لخدمات الشركة.</p><button class="outline" data-action="new-idea">خطّط حملة مناسبة الآن ←</button>';
  $('#ideas-view').innerHTML=completed?campaignCard(completed):'<div class="idea-number">—</div><div><span class="tag">الفكرة الموصى بها</span><h2>بانتظار بحث حقيقي</h2><p>أنشئ حملة، وسيجمع XPAND مراجع متاحة ويطوّر اتجاهًا واحدًا قابلًا للتنفيذ مع القيود والمصادر.</p></div><button class="primary small" data-action="new-idea">أنشئ حملة ←</button>';
}
function campaignCard(c){const r=c.result||{};return `<div class="idea-number">01</div><div><span class="tag">فكرة موصى بها</span><h2>${esc(r.الاسم||'حملة XPAND')}</h2><p>${esc(r.الفكرة_الإبداعية||'')}</p><div class="idea-meta"><span>${esc(r.الخدمة||'')}</span><span>${esc(r.النوع||'')}</span></div></div><button class="primary small" data-action="open-campaign" data-id="${c.id}">التفاصيل ←</button>`}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function stageText(s){return({queued:'بانتظار بدء المهمة',collecting_references:'جمع مراجع قابلة للتتبع',developing_concept:'تطوير الاتجاه الإبداعي',saving_plan:'حفظ خطة التنفيذ'})[s]||'معالجة الحملة'}
async function load(){try{render(await api('/api/content/dashboard'));const active=state.campaigns.some(c=>['queued','running'].includes(c.status));clearTimeout(poll);if(active)poll=setTimeout(load,6000)}catch(e){$('.alerts').innerHTML=`<b>تعذر الوصول الآمن</b><p>${esc(e.message)}</p>`;$('#task-list').innerHTML='<p class="empty">افتح الأداة من زر تيليجرام لتتحقق هويتك وتظهر سجلاتك الفعلية.</p>';$('.occasion-card').innerHTML='<h2>بيانات حقيقية فقط</h2><p>لا توجد مناسبات أو مهام افتراضية.</p>';$('#ideas-view').innerHTML='<div><h2>لا توجد فكرة محفوظة</h2><p>ابدأ من زر «أنشئ حملة جديدة» داخل تيليجرام.</p></div>'}}
function openDialog(title,body){$('#dialog-content').innerHTML=`<p class="eyebrow">XPAND CONTENT COMMAND</p><h2>${title}</h2>${body}`;dialog.showModal()}
document.addEventListener('click',async e=>{const a=e.target.closest('[data-action]');if(a){const x=a.dataset.action;if(x==='new-idea')openDialog('أنشئ حملة جديدة',`<p>اكتب الهدف أو الخدمة. يبدأ XPAND مهمة بحث وتطوير حقيقية في الخلفية، ثم يحفظ فكرة واحدة وخطة تنفيذ ومراجعها.</p><label>طلب الحملة<input id="campaign-input" placeholder="مثال: بدي حملة تجيب استفسارات لخدمة الفيديو الإعلاني"/></label><button class="primary dialog-submit" data-action="save-campaign">ابدأ البحث والتطوير ←</button>`);if(x==='save-campaign'){const request=$('#campaign-input').value.trim();try{await api('/api/content/campaigns',{method:'POST',body:JSON.stringify({request})});dialog.close();toast('بدأت مهمة الحملة وحُفظت. سنعرض مراحلها الفعلية هنا.');load()}catch(err){toast(err.message)}}if(x==='refresh')load();if(x==='close-dialog')dialog.close();if(x==='open-campaign'){const c=state.campaigns.find(z=>z.id===a.dataset.id),r=c?.result||{};openDialog(r.الاسم||'تفاصيل الحملة',`<p><b>الهدف:</b> ${esc(r.الهدف||'')}</p><p><b>الرسالة:</b> ${esc(r.الرسالة||'')}</p><p><b>الافتتاحية:</b> ${esc(r.الافتتاحية||'')}</p><p><b>التنفيذ:</b> ${esc(r.تعليمات_التنفيذ||'')}</p><p class="hint">القيود: ${esc(c.limitations||r.افتراضات_وقيود||'لا توجد قيود مسجلة.')}</p>`);}}
  const tb=e.target.closest('[data-task]');if(tb){const current=tb.dataset.status;const next=current==='awaiting_start'?'in_production':current==='in_production'?'in_review':current==='in_review'?'ready_to_publish':current==='ready_to_publish'?'published':'in_production';try{await api(`/api/content/tasks/${tb.dataset.task}`,{method:'PATCH',body:JSON.stringify({status:next})});toast(`تم تحديث الحالة إلى: ${stateLabel(next)}`);load()}catch(err){toast(err.message)}}
  const v=e.target.closest('[data-view]')?.dataset.view;if(v){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===v));const target=v==='tasks'?'#today-card':v==='ideas'?'#ideas-view':v==='calendar'?'#calendar-view':'.hero';$(target).scrollIntoView({behavior:'smooth',block:'start'})}});load();setInterval(()=>{if(state.now)load()},60000);
